name: timfeirg
description: "low tech"
meta_description: ""

markdown: kramdown
highlighter: rouge
logo: /assets/images/me.ico
paginate: 15
baseurl: ""
domain_name: "http://timfeirg.github.io"
google_analytics: "UA-112067081-1"
plugins:
  - jekyll-paginate
  - jekyll-feed

# Details for the RSS feed generator
url: ""
author: "timfeirg"

# Disqus config
disqus-shortname: ""
