name: timfeirg
description: ""
meta_description: ""

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ""
domain_name: "http://timfeirg.github.io"
google_analytics: "UA-112067081-1"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "timfeirg"

# Disqus config
disqus-shortname: ""
